### ISSUE TITLE
extension  found.

### ISSUE THREAD

**Issue by jaffarc** [eridem/vscode-postman#2]
could help configure the plugin? I exported the file already json to root and yet this error
extension "postman_collection.json" found.

**Comment by eridem** [comment]
Hi @jaffarc,

Try to use a name for the file and use `postman_collection.json` as suffix on your file. E.g.

```
my_api.postman_collection.json
```

At the current moment, the file cannot be called simply `postman_collection.json` because it try to find files with the form `*.postman_collection.json`.

Let me know if it works with that rename.

**Comment by jaffarc** [comment]
thanks for the help, it worked
